// Code generated by MockGen. DO NOT EDIT.
// Source: service-courier/internal/handler/courier (interfaces: courierService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/courier_service_mock.go -package=mocks service-courier/internal/handler/courier courierService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	courier "service-courier/internal/model/courier"

	gomock "go.uber.org/mock/gomock"
)

// MockcourierService is a mock of courierService interface.
type MockcourierService struct {
	ctrl     *gomock.Controller
	recorder *MockcourierServiceMockRecorder
	isgomock struct{}
}

// MockcourierServiceMockRecorder is the mock recorder for MockcourierService.
type MockcourierServiceMockRecorder struct {
	mock *MockcourierService
}

// NewMockcourierService creates a new mock instance.
func NewMockcourierService(ctrl *gomock.Controller) *MockcourierService {
	mock := &MockcourierService{ctrl: ctrl}
	mock.recorder = &MockcourierServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierService) EXPECT() *MockcourierServiceMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockcourierService) CreateCourier(ctx context.Context, courierData courier.Courier) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", ctx, courierData)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockcourierServiceMockRecorder) CreateCourier(ctx, courierData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockcourierService)(nil).CreateCourier), ctx, courierData)
}

// GetAllCouriers mocks base method.
func (m *MockcourierService) GetAllCouriers(ctx context.Context) ([]courier.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCouriers", ctx)
	ret0, _ := ret[0].([]courier.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCouriers indicates an expected call of GetAllCouriers.
func (mr *MockcourierServiceMockRecorder) GetAllCouriers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCouriers", reflect.TypeOf((*MockcourierService)(nil).GetAllCouriers), ctx)
}

// GetCourier mocks base method.
func (m *MockcourierService) GetCourier(ctx context.Context, id int64) (*courier.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourier", ctx, id)
	ret0, _ := ret[0].(*courier.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourier indicates an expected call of GetCourier.
func (mr *MockcourierServiceMockRecorder) GetCourier(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourier", reflect.TypeOf((*MockcourierService)(nil).GetCourier), ctx, id)
}

// UpdateCourier mocks base method.
func (m *MockcourierService) UpdateCourier(ctx context.Context, courierData courier.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, courierData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockcourierServiceMockRecorder) UpdateCourier(ctx, courierData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockcourierService)(nil).UpdateCourier), ctx, courierData)
}
