// Code generated by MockGen. DO NOT EDIT.
// Source: service-courier/internal/service/delivery (interfaces: courierRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/delivery_courier_repo_mock.go -package=mocks service-courier/internal/service/delivery courierRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	courier "service-courier/internal/model/courier"

	gomock "go.uber.org/mock/gomock"
)

// MockDeliveryCourierRepository is a mock of courierRepository interface from delivery service.
type MockDeliveryCourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryCourierRepositoryMockRecorder
	isgomock struct{}
}

// MockDeliveryCourierRepositoryMockRecorder is the mock recorder for MockDeliveryCourierRepository.
type MockDeliveryCourierRepositoryMockRecorder struct {
	mock *MockDeliveryCourierRepository
}

// NewMockDeliveryCourierRepository creates a new mock instance.
func NewMockDeliveryCourierRepository(ctrl *gomock.Controller) *MockDeliveryCourierRepository {
	mock := &MockDeliveryCourierRepository{ctrl: ctrl}
	mock.recorder = &MockDeliveryCourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryCourierRepository) EXPECT() *MockDeliveryCourierRepositoryMockRecorder {
	return m.recorder
}

// GetAvailableWithMinDeliveries mocks base method.
func (m *MockDeliveryCourierRepository) GetAvailableWithMinDeliveries(ctx context.Context) (*courier.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableWithMinDeliveries", ctx)
	ret0, _ := ret[0].(*courier.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableWithMinDeliveries indicates an expected call of GetAvailableWithMinDeliveries.
func (mr *MockDeliveryCourierRepositoryMockRecorder) GetAvailableWithMinDeliveries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableWithMinDeliveries", reflect.TypeOf((*MockDeliveryCourierRepository)(nil).GetAvailableWithMinDeliveries), ctx)
}

// GetByID mocks base method.
func (m *MockDeliveryCourierRepository) GetByID(ctx context.Context, id int64) (*courier.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*courier.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeliveryCourierRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeliveryCourierRepository)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockDeliveryCourierRepository) Update(ctx context.Context, courierData courier.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, courierData)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeliveryCourierRepositoryMockRecorder) Update(ctx, courierData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeliveryCourierRepository)(nil).Update), ctx, courierData)
}

// UpdateStatusBatch mocks base method.
func (m *MockDeliveryCourierRepository) UpdateStatusBatch(ctx context.Context, ids []int64, status courier.CourierStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusBatch", ctx, ids, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusBatch indicates an expected call of UpdateStatusBatch.
func (mr *MockDeliveryCourierRepositoryMockRecorder) UpdateStatusBatch(ctx, ids, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusBatch", reflect.TypeOf((*MockDeliveryCourierRepository)(nil).UpdateStatusBatch), ctx, ids, status)
}
