// Code generated by MockGen. DO NOT EDIT.
// Source: service-courier/internal/service/delivery (interfaces: courierRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/courier_repository_mock.go -package=mocks service-courier/internal/service/delivery courierRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	courier "service-courier/internal/model/courier"

	gomock "go.uber.org/mock/gomock"
)

// MockcourierRepository is a mock of courierRepository interface.
type MockcourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcourierRepositoryMockRecorder
	isgomock struct{}
}

// MockcourierRepositoryMockRecorder is the mock recorder for MockcourierRepository.
type MockcourierRepositoryMockRecorder struct {
	mock *MockcourierRepository
}

// NewMockcourierRepository creates a new mock instance.
func NewMockcourierRepository(ctrl *gomock.Controller) *MockcourierRepository {
	mock := &MockcourierRepository{ctrl: ctrl}
	mock.recorder = &MockcourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierRepository) EXPECT() *MockcourierRepositoryMockRecorder {
	return m.recorder
}

// GetAvailableWithMinDeliveries mocks base method.
func (m *MockcourierRepository) GetAvailableWithMinDeliveries(ctx context.Context) (*courier.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableWithMinDeliveries", ctx)
	ret0, _ := ret[0].(*courier.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableWithMinDeliveries indicates an expected call of GetAvailableWithMinDeliveries.
func (mr *MockcourierRepositoryMockRecorder) GetAvailableWithMinDeliveries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableWithMinDeliveries", reflect.TypeOf((*MockcourierRepository)(nil).GetAvailableWithMinDeliveries), ctx)
}

// GetByID mocks base method.
func (m *MockcourierRepository) GetByID(ctx context.Context, id int64) (*courier.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*courier.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockcourierRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockcourierRepository)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockcourierRepository) Update(ctx context.Context, courierData courier.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, courierData)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockcourierRepositoryMockRecorder) Update(ctx, courierData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockcourierRepository)(nil).Update), ctx, courierData)
}

// UpdateStatusBatch mocks base method.
func (m *MockcourierRepository) UpdateStatusBatch(ctx context.Context, ids []int64, status courier.CourierStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusBatch", ctx, ids, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusBatch indicates an expected call of UpdateStatusBatch.
func (mr *MockcourierRepositoryMockRecorder) UpdateStatusBatch(ctx, ids, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusBatch", reflect.TypeOf((*MockcourierRepository)(nil).UpdateStatusBatch), ctx, ids, status)
}
