// Code generated by MockGen. DO NOT EDIT.
// Source: service-courier/internal/service/delivery (interfaces: deliveryRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/delivery_repository_mock.go -package=mocks service-courier/internal/service/delivery deliveryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	delivery "service-courier/internal/model/delivery"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockdeliveryRepository is a mock of deliveryRepository interface.
type MockdeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryRepositoryMockRecorder
	isgomock struct{}
}

// MockdeliveryRepositoryMockRecorder is the mock recorder for MockdeliveryRepository.
type MockdeliveryRepositoryMockRecorder struct {
	mock *MockdeliveryRepository
}

// NewMockdeliveryRepository creates a new mock instance.
func NewMockdeliveryRepository(ctrl *gomock.Controller) *MockdeliveryRepository {
	mock := &MockdeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockdeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryRepository) EXPECT() *MockdeliveryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockdeliveryRepository) Create(ctx context.Context, deliveryData delivery.Delivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, deliveryData)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockdeliveryRepositoryMockRecorder) Create(ctx, deliveryData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockdeliveryRepository)(nil).Create), ctx, deliveryData)
}

// DeleteByOrderID mocks base method.
func (m *MockdeliveryRepository) DeleteByOrderID(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByOrderID", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByOrderID indicates an expected call of DeleteByOrderID.
func (mr *MockdeliveryRepositoryMockRecorder) DeleteByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByOrderID", reflect.TypeOf((*MockdeliveryRepository)(nil).DeleteByOrderID), ctx, orderID)
}

// GetByOrderID mocks base method.
func (m *MockdeliveryRepository) GetByOrderID(ctx context.Context, orderID string) (*delivery.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*delivery.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderID indicates an expected call of GetByOrderID.
func (mr *MockdeliveryRepositoryMockRecorder) GetByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderID", reflect.TypeOf((*MockdeliveryRepository)(nil).GetByOrderID), ctx, orderID)
}

// ListActiveExpired mocks base method.
func (m *MockdeliveryRepository) ListActiveExpired(ctx context.Context, now time.Time) ([]delivery.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveExpired", ctx, now)
	ret0, _ := ret[0].([]delivery.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveExpired indicates an expected call of ListActiveExpired.
func (mr *MockdeliveryRepositoryMockRecorder) ListActiveExpired(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveExpired", reflect.TypeOf((*MockdeliveryRepository)(nil).ListActiveExpired), ctx, now)
}

// UpdateStatusByIDs mocks base method.
func (m *MockdeliveryRepository) UpdateStatusByIDs(ctx context.Context, ids []int64, status delivery.DeliveryStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusByIDs", ctx, ids, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusByIDs indicates an expected call of UpdateStatusByIDs.
func (mr *MockdeliveryRepositoryMockRecorder) UpdateStatusByIDs(ctx, ids, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusByIDs", reflect.TypeOf((*MockdeliveryRepository)(nil).UpdateStatusByIDs), ctx, ids, status)
}
