// Code generated by MockGen. DO NOT EDIT.
// Source: service-courier/internal/service/delivery (interfaces: transactionManager)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/transaction_manager_mock.go -package=mocks service-courier/internal/service/delivery transactionManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocktransactionManager is a mock of transactionManager interface.
type MocktransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionManagerMockRecorder
	isgomock struct{}
}

// MocktransactionManagerMockRecorder is the mock recorder for MocktransactionManager.
type MocktransactionManagerMockRecorder struct {
	mock *MocktransactionManager
}

// NewMocktransactionManager creates a new mock instance.
func NewMocktransactionManager(ctrl *gomock.Controller) *MocktransactionManager {
	mock := &MocktransactionManager{ctrl: ctrl}
	mock.recorder = &MocktransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionManager) EXPECT() *MocktransactionManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MocktransactionManager) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MocktransactionManagerMockRecorder) Do(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MocktransactionManager)(nil).Do), ctx, fn)
}
