// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/delivery_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	delivery "service-courier/internal/service/delivery"

	gomock "go.uber.org/mock/gomock"
)

// MockdeliveryService is a mock of deliveryService interface.
type MockdeliveryService struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryServiceMockRecorder
	isgomock struct{}
}

// MockdeliveryServiceMockRecorder is the mock recorder for MockdeliveryService.
type MockdeliveryServiceMockRecorder struct {
	mock *MockdeliveryService
}

// NewMockdeliveryService creates a new mock instance.
func NewMockdeliveryService(ctrl *gomock.Controller) *MockdeliveryService {
	mock := &MockdeliveryService{ctrl: ctrl}
	mock.recorder = &MockdeliveryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryService) EXPECT() *MockdeliveryServiceMockRecorder {
	return m.recorder
}

// AssignCourier mocks base method.
func (m *MockdeliveryService) AssignCourier(ctx context.Context, orderID string) (*delivery.AssignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCourier", ctx, orderID)
	ret0, _ := ret[0].(*delivery.AssignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignCourier indicates an expected call of AssignCourier.
func (mr *MockdeliveryServiceMockRecorder) AssignCourier(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCourier", reflect.TypeOf((*MockdeliveryService)(nil).AssignCourier), ctx, orderID)
}

// UnassignCourier mocks base method.
func (m *MockdeliveryService) UnassignCourier(ctx context.Context, orderID string) (*delivery.UnassignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignCourier", ctx, orderID)
	ret0, _ := ret[0].(*delivery.UnassignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignCourier indicates an expected call of UnassignCourier.
func (mr *MockdeliveryServiceMockRecorder) UnassignCourier(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignCourier", reflect.TypeOf((*MockdeliveryService)(nil).UnassignCourier), ctx, orderID)
}
