{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество запросов по методам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method) (\n  increase(http_requests_total{path!=\"/metrics\"}[$__range])\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Количество запросов по статусам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status_code) (\n  increase(http_requests_total{path!=\"/metrics\"}[$__range])\n)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Общее количество операций",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(operations_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество запросов по эндпоинтам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (path) (\n  increase(http_requests_total{path!=\"/metrics\"}[$__range])\n)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}